Using GitHub CLI in Workflows

diff --git a/.github/workflows/example07.yml b/.github/workflows/example07.yml
--- a/.github/workflows/example07.yml
+++ b/.github/workflows/example07.yml
@@ -7,5 +7,6 @@ jobs:
     runs-on: ubuntu-latest
     steps:
       - run: |
-          echo "::error Intentional Error::Missing Semicolon"
-          exit 1
+#          echo "::error Intentional Error::Missing Semicolon"
+#          exit 1
+           echo "$GITHUB_STEP_SUMMARY"
